from __future__ import annotations

import json
from pathlib import Path

from kvrm_bench.publication_paper_assets import (
    build_publication_paper_appendix,
    build_publication_paper_assets,
)


REPO_ROOT = Path(__file__).resolve().parents[2]


def test_build_publication_paper_assets_reads_live_summary_and_writes_tables_and_captions(
    tmp_path: Path,
) -> None:
    result = build_publication_paper_assets(REPO_ROOT, output_dir=tmp_path)

    json_path = Path(result["path"])
    tables_path = Path(result["tables_path"])
    captions_path = Path(result["captions_path"])

    assert json_path.exists()
    assert tables_path.exists()
    assert captions_path.exists()

    payload = json.loads(json_path.read_text(encoding="utf-8"))
    assert len(payload["tables"]) >= 5
    assert len(payload["figures"]) == 7
    assert payload["tables"][0]["title"] == "Canonical Seven-Domain Hybrid KVRM Results"
    assert payload["figures"][3]["title"] == "Seven-domain canonical benchmark summary"
    assert payload["figures"][6]["file"] == "docs/figures/fig7_robustness_families.svg"

    tables_markdown = tables_path.read_text(encoding="utf-8")
    assert "# KVRM Paper Tables" in tables_markdown
    assert "Table 1. Canonical Seven-Domain Hybrid KVRM Results" in tables_markdown
    assert "| Domain | Cases | Semantic | False Accept | Unsupported Reject | Invalid Output |" in tables_markdown
    assert "gemma4:e2b" in tables_markdown

    captions_markdown = captions_path.read_text(encoding="utf-8")
    assert "# KVRM Figure Captions" in captions_markdown
    assert "Figure 4: Seven-domain canonical benchmark summary" in captions_markdown
    assert "Figure 7: Replay, counterfactual, temporal, and coordination robustness summary" in captions_markdown


def test_build_publication_paper_appendix_writes_bundle_and_docs_markdown(tmp_path: Path) -> None:
    docs_path = tmp_path / "docs" / "KVRM_PUBLICATION_APPENDIX.md"
    result = build_publication_paper_appendix(
        REPO_ROOT,
        output_dir=tmp_path,
        docs_output_path=docs_path,
    )

    appendix_path = Path(result["path"])
    assert appendix_path.exists()
    assert docs_path.exists()
    assert result["docs_path"] == str(docs_path)

    appendix_markdown = appendix_path.read_text(encoding="utf-8")
    assert "# KVRM Publication Appendix" in appendix_markdown
    assert "Do not edit this file by hand." in appendix_markdown
    assert "### Table 1. Canonical Seven-Domain Hybrid KVRM Results" in appendix_markdown
    assert "| iam | 24 | 1.0000 | 0.0000 | 1.0000 | 0.0000 |" in appendix_markdown
    assert "### Figure 4: Seven-domain canonical benchmark summary" in appendix_markdown
    assert "`docs/figures/fig4_canonical_suite.svg`" in appendix_markdown
    assert "`kvrm-bench/results/publication_bundle/paper_appendix.md`" in appendix_markdown

    docs_markdown = docs_path.read_text(encoding="utf-8")
    assert docs_markdown == appendix_markdown
