/**
 * Assembly Emitter for KVRM Code Generator
 * Formats and emits KVRM assembly code
 */

import type { KVRMInstruction } from './instruction-selector.js';
import type { IRProgram } from '../ir/types.js';
import type { KVRMRegister } from './register-allocator.js';
import { RegisterAllocator } from './register-allocator.js';

/**
 * Assembly section types
 */
export enum AsmSection {
  Text = '.text',
  Data = '.data',
  Rodata = '.rodata',
  Bss = '.bss',
}

/**
 * Assembly directive
 */
export interface AsmDirective {
  type: 'directive';
  name: string;
  args?: string[];
}

/**
 * Assembly label
 */
export interface AsmLabel {
  type: 'label';
  name: string;
  global?: boolean;
}

/**
 * Assembly data declaration
 */
export interface AsmData {
  type: 'data';
  size: 'byte' | 'word' | 'dword' | 'string';
  values: (number | string)[];
  label?: string;
}

/**
 * Assembly output line
 */
export type AsmLine = KVRMInstruction | AsmDirective | AsmLabel | AsmData | { type: 'comment'; text: string } | { type: 'blank' };

/**
 * Formatting options
 */
export interface FormatOptions {
  indent: string;
  commentColumn: number;
  uppercase: boolean;
  includeAddresses: boolean;
}

/**
 * Assembly Emitter - Formats and outputs assembly code
 */
export class AssemblyEmitter {
  private lines: AsmLine[] = [];
  private currentSection: AsmSection | null = null;
  private options: FormatOptions;

  constructor(options: Partial<FormatOptions> = {}) {
    this.options = {
      indent: '    ',
      commentColumn: 40,
      uppercase: true,
      includeAddresses: false,
      ...options,
    };
  }

  /**
   * Emit program preamble
   */
  public emitPreamble(entryPoint: string = 'main'): void {
    this.emitComment('KVRM Assembly Output');
    this.emitComment('Generated by KVRM Compiler');
    this.emitBlank();
    this.emitDirective('.arch', ['kvrm']);
    this.emitDirective('.global', [entryPoint]);
    this.emitBlank();
  }

  /**
   * Switch to a section
   */
  public emitSection(section: AsmSection): void {
    if (this.currentSection !== section) {
      this.emitBlank();
      this.emitDirective(section);
      this.currentSection = section;
    }
  }

  /**
   * Emit a directive
   */
  public emitDirective(name: string, args?: string[]): void {
    this.lines.push({ type: 'directive', name, args });
  }

  /**
   * Emit a label
   */
  public emitLabel(name: string, global: boolean = false): void {
    this.lines.push({ type: 'label', name, global });
  }

  /**
   * Emit an instruction
   */
  public emitInstruction(instr: KVRMInstruction): void {
    this.lines.push(instr);
  }

  /**
   * Emit multiple instructions
   */
  public emitInstructions(instrs: KVRMInstruction[]): void {
    instrs.forEach(instr => this.emitInstruction(instr));
  }

  /**
   * Emit data declaration
   */
  public emitData(size: 'byte' | 'word' | 'dword' | 'string', values: (number | string)[], label?: string): void {
    this.lines.push({ type: 'data', size, values, label });
  }

  /**
   * Emit a comment
   */
  public emitComment(text: string): void {
    this.lines.push({ type: 'comment', text });
  }

  /**
   * Emit blank line
   */
  public emitBlank(): void {
    this.lines.push({ type: 'blank' });
  }

  /**
   * Emit function prologue
   */
  public emitFunctionPrologue(
    funcName: string,
    stackFrameSize: number,
    savedRegisters: Set<KVRMRegister>,
    isGlobal: boolean = false
  ): void {
    // Function label
    if (isGlobal) {
      this.emitDirective('.global', [funcName]);
    }
    this.emitLabel(funcName);
    this.emitComment(`Function: ${funcName}`);

    // Save link register (return address)
    this.emitInstruction({
      mnemonic: 'PUSH',
      operands: ['LR'],
      comment: 'Save return address',
    });

    // Save frame pointer
    this.emitInstruction({
      mnemonic: 'PUSH',
      operands: ['R14'],
      comment: 'Save frame pointer',
    });

    // Set up new frame pointer
    this.emitInstruction({
      mnemonic: 'MOV',
      operands: ['R14', 'SP'],
      comment: 'Set up frame pointer',
    });

    // Save callee-saved registers
    if (savedRegisters.size > 0) {
      const regs = Array.from(savedRegisters)
        .sort((a, b) => a - b)
        .map(reg => RegisterAllocator.getRegisterName(reg));

      this.emitComment('Save callee-saved registers');
      regs.forEach(reg => {
        this.emitInstruction({ mnemonic: 'PUSH', operands: [reg] });
      });
    }

    // Allocate stack space for locals and spills
    if (stackFrameSize > 0) {
      this.emitInstruction({
        mnemonic: 'SUB',
        operands: ['SP', 'SP', `#${stackFrameSize}`],
        comment: `Allocate ${stackFrameSize} bytes for locals`,
      });
    }
  }

  /**
   * Emit function epilogue
   */
  public emitFunctionEpilogue(stackFrameSize: number, savedRegisters: Set<KVRMRegister>): void {
    this.emitComment('Function epilogue');

    // Deallocate stack frame
    if (stackFrameSize > 0) {
      this.emitInstruction({
        mnemonic: 'ADD',
        operands: ['SP', 'SP', `#${stackFrameSize}`],
        comment: 'Deallocate locals',
      });
    }

    // Restore callee-saved registers (in reverse order)
    if (savedRegisters.size > 0) {
      const regs = Array.from(savedRegisters)
        .sort((a, b) => b - a)
        .map(reg => RegisterAllocator.getRegisterName(reg));

      this.emitComment('Restore callee-saved registers');
      regs.forEach(reg => {
        this.emitInstruction({ mnemonic: 'POP', operands: [reg] });
      });
    }

    // Restore frame pointer
    this.emitInstruction({
      mnemonic: 'POP',
      operands: ['R14'],
      comment: 'Restore frame pointer',
    });

    // Restore link register
    this.emitInstruction({
      mnemonic: 'POP',
      operands: ['LR'],
      comment: 'Restore return address',
    });

    // Return
    this.emitInstruction({ mnemonic: 'RET', operands: [] });
  }

  /**
   * Emit data section for program
   */
  public emitDataSection(program: IRProgram): void {
    // String literals
    if (program.stringLiterals.size > 0) {
      this.emitSection(AsmSection.Rodata);
      this.emitComment('String literals');

      for (const [label, value] of program.stringLiterals) {
        this.emitData('string', [value], label);
      }
    }

    // Global variables
    if (program.globals.size > 0) {
      this.emitSection(AsmSection.Data);
      this.emitComment('Global variables');

      for (const [name, info] of program.globals) {
        if (info.initialValue) {
          const value = info.initialValue.kind === 'constant' ? info.initialValue.value : 0;
          this.emitData('dword', [value as number], name);
        } else {
          // Uninitialized globals go in BSS
          this.emitSection(AsmSection.Bss);
          this.emitDirective('.lcomm', [name, '4']); // 4 bytes
        }
      }
    }

    // Constants
    if (program.constants.size > 0) {
      this.emitSection(AsmSection.Rodata);
      this.emitComment('Constants');

      for (const [name, info] of program.constants) {
        this.emitData('dword', [info.value], name);
      }
    }
  }

  /**
   * Format and return complete assembly output
   */
  public toString(): string {
    const output: string[] = [];

    for (const line of this.lines) {
      output.push(this.formatLine(line));
    }

    return output.join('\n');
  }

  /**
   * Format a single assembly line
   */
  private formatLine(line: AsmLine): string {
    switch (line.type) {
      case 'directive':
        return this.formatDirective(line);
      case 'label':
        return this.formatLabel(line);
      case 'data':
        return this.formatData(line);
      case 'comment':
        return this.formatComment(line.text);
      case 'blank':
        return '';
      default:
        return this.formatInstruction(line);
    }
  }

  /**
   * Format directive
   */
  private formatDirective(directive: AsmDirective): string {
    const name = directive.name;
    const args = directive.args ? ' ' + directive.args.join(', ') : '';
    return `${name}${args}`;
  }

  /**
   * Format label
   */
  private formatLabel(label: AsmLabel): string {
    const prefix = label.global ? '.global ' + label.name + '\n' : '';
    return prefix + label.name + ':';
  }

  /**
   * Format data declaration
   */
  private formatData(data: AsmData): string {
    const parts: string[] = [];

    if (data.label) {
      parts.push(data.label + ':');
    }

    const directive = {
      byte: '.byte',
      word: '.word',
      dword: '.dword',
      string: '.string',
    }[data.size];

    const values = data.values.map(v => {
      if (typeof v === 'string') {
        return `"${v.replace(/"/g, '\\"')}"`;
      }
      return v.toString();
    });

    const dataLine = `${this.options.indent}${directive} ${values.join(', ')}`;
    parts.push(dataLine);

    return parts.join('\n');
  }

  /**
   * Format instruction
   */
  private formatInstruction(instr: KVRMInstruction): string {
    let mnemonic = instr.mnemonic;

    // Handle labels (mnemonic ends with ':')
    if (mnemonic.endsWith(':')) {
      return mnemonic;
    }

    // Apply case preference
    if (this.options.uppercase) {
      mnemonic = mnemonic.toUpperCase();
    } else {
      mnemonic = mnemonic.toLowerCase();
    }

    // Format operands
    const operands = instr.operands.join(', ');

    // Build instruction string
    let line = this.options.indent + mnemonic;
    if (operands) {
      // Pad mnemonic to align operands
      line = line.padEnd(12, ' ') + operands;
    }

    // Add comment if present
    if (instr.comment) {
      const commentStart = Math.max(line.length + 2, this.options.commentColumn);
      line = line.padEnd(commentStart, ' ') + '; ' + instr.comment;
    }

    return line;
  }

  /**
   * Format standalone comment
   */
  private formatComment(text: string): string {
    return `; ${text}`;
  }

  /**
   * Clear all emitted lines
   */
  public clear(): void {
    this.lines = [];
    this.currentSection = null;
  }

  /**
   * Get all emitted lines
   */
  public getLines(): readonly AsmLine[] {
    return this.lines;
  }
}
