/**
 * KVRM Code Generator - Production Quality
 * Generates assembly code for KVRM CPU architecture from IR
 *
 * KVRM CPU Specifications:
 * - 16 general-purpose 32-bit registers: R0-R15
 * - R15 = PC (Program Counter)
 * - R14 = SP (Stack Pointer)
 * - R13 = LR (Link Register)
 * - Memory is byte-addressable
 * - Load/Store architecture
 */

import type {
  IRProgram,
  IRFunction,
  IRBlock,
  IRInstr,
  IRValue,
  IRBinOp,
  IRUnaryOp,
  IRCall,
  IRLoad,
  IRStore,
  IRConst,
  IRReturn,
  IRJump,
  IRCondJump,
  IRAlloc,
  BinOpKind,
  UnaryOpKind,
} from '../ir/ir-nodes.js';

import { RegisterAllocator, KVRMRegister } from './register-allocator.js';

/**
 * Register names for assembly output
 */
const REG_NAMES = [
  'R0', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7',
  'R8', 'R9', 'R10', 'R11', 'R12', 'LR', 'SP', 'PC',
];

/**
 * Code generation context
 */
interface CodeGenContext {
  valueToReg: Map<number, number>; // Maps SSA value ID to register
  valueToStack: Map<number, number>; // Maps SSA value ID to stack offset
  currentStackOffset: number;
  spilledValues: Set<number>;
  output: string[];
  indent: string;
}

/**
 * Live range information for register allocation
 */
interface LiveRange {
  valueId: number;
  start: number;
  end: number;
}

/**
 * KVRM Code Generator
 */
export class KVRMCodeGenerator {
  private context: CodeGenContext;
  private labelCounter: number = 0;

  constructor() {
    this.context = {
      valueToReg: new Map(),
      valueToStack: new Map(),
      currentStackOffset: 0,
      spilledValues: new Set(),
      output: [],
      indent: '    ',
    };
  }

  /**
   * Generate assembly code for entire program
   */
  public generate(program: IRProgram): string {
    this.reset();

    this.emit('; KVRM Assembly Output');
    this.emit('; Generated by KVRM Compiler');
    this.emit('');

    // Find entry point
    const mainFunc = program.functions.find(f => f.name === 'main');
    if (mainFunc) {
      this.emit('.global main');
    }

    // Emit global variables
    if (program.globals && program.globals.length > 0) {
      this.emit('');
      this.emit('.section .data');
      for (const global of program.globals) {
        this.emit(`${global.name}: .word 0    ; Global variable`);
      }
    }

    // Emit functions
    this.emit('');
    this.emit('.section .text');

    for (const func of program.functions) {
      this.emit('');
      this.generateFunction(func);
    }

    return this.context.output.join('\n');
  }

  /**
   * Generate code for a function
   */
  private generateFunction(func: IRFunction): void {
    this.emit(`;  ========================================`);
    this.emit(`; Function: ${func.name}`);
    this.emit(`;  ========================================`);
    this.emit(`${func.name}:`);

    // Function prologue
    this.emitPrologue(func);

    // Generate code for each block
    const blocks = this.orderBlocks(func);

    for (const block of blocks) {
      // Skip entry block label (it's the function name)
      if (block.label !== func.entryBlock) {
        this.emit(`${block.label}:`);
      }

      for (const instr of block.instructions) {
        this.generateInstruction(instr, func);
      }
    }
  }

  /**
   * Emit function prologue
   */
  private emitPrologue(func: IRFunction): void {
    this.emitIndented('PUSH LR', 'Save return address');
    this.emitIndented('PUSH R14', 'Save frame pointer');
    this.emitIndented('MOV R14, SP', 'Setup frame pointer');

    // Calculate stack space needed
    const stackSpace = this.calculateStackSpace(func);
    if (stackSpace > 0) {
      this.emitIndented(`SUB SP, SP, #${stackSpace}`, `Allocate ${stackSpace} bytes`);
    }
  }

  /**
   * Emit function epilogue
   */
  private emitEpilogue(func: IRFunction): void {
    const stackSpace = this.calculateStackSpace(func);
    if (stackSpace > 0) {
      this.emitIndented(`ADD SP, SP, #${stackSpace}`, 'Deallocate locals');
    }

    this.emitIndented('POP R14', 'Restore frame pointer');
    this.emitIndented('POP LR', 'Restore return address');
    this.emitIndented('RET', 'Return');
  }

  /**
   * Generate code for a single instruction
   */
  private generateInstruction(instr: IRInstr, func: IRFunction): void {
    switch (instr.kind) {
      case 'const':
        this.genConst(instr as IRConst);
        break;
      case 'binop':
        this.genBinOp(instr as IRBinOp);
        break;
      case 'unaryop':
        this.genUnaryOp(instr as IRUnaryOp);
        break;
      case 'load':
        this.genLoad(instr as IRLoad);
        break;
      case 'store':
        this.genStore(instr as IRStore);
        break;
      case 'call':
        this.genCall(instr as IRCall, func);
        break;
      case 'return':
        this.genReturn(instr as IRReturn, func);
        break;
      case 'jump':
        this.genJump(instr as IRJump);
        break;
      case 'condjump':
        this.genCondJump(instr as IRCondJump);
        break;
      case 'alloc':
        this.genAlloc(instr as IRAlloc);
        break;
      default:
        this.emit(`; TODO: ${instr.kind}`);
    }
  }

  /**
   * Generate constant load
   */
  private genConst(instr: IRConst): void {
    const dest = this.allocateRegister(instr.result.id);
    const value = instr.value;

    if (typeof value === 'number') {
      if (value >= -2048 && value <= 2047) {
        this.emitIndented(`MOV ${dest}, #${value}`);
      } else {
        // Large immediate requires multiple instructions
        const upper = (value >>> 16) & 0xFFFF;
        const lower = value & 0xFFFF;
        this.emitIndented(`MOVH ${dest}, #${upper}`, 'Load upper 16 bits');
        if (lower !== 0) {
          this.emitIndented(`OR ${dest}, ${dest}, #${lower}`, 'Load lower 16 bits');
        }
      }
    } else if (typeof value === 'boolean') {
      this.emitIndented(`MOV ${dest}, #${value ? 1 : 0}`);
    } else {
      // String constant - load address
      const label = this.getStringLabel(value as string);
      this.emitIndented(`LEA ${dest}, ${label}`);
    }
  }

  /**
   * Generate binary operation
   */
  private genBinOp(instr: IRBinOp): void {
    const dest = this.allocateRegister(instr.result.id);
    const left = this.getOperand(instr.left.id);
    const right = this.getOperand(instr.right.id);

    const opMap: Record<BinOpKind, string> = {
      'add': 'ADD',
      'sub': 'SUB',
      'mul': 'MUL',
      'div': 'DIV',
      'mod': 'MOD',
      'bitand': 'AND',
      'bitor': 'OR',
      'bitxor': 'XOR',
      'shl': 'SHL',
      'shr': 'SHR',
      // Comparisons require special handling
      'eq': 'EQ',
      'ne': 'NE',
      'lt': 'LT',
      'le': 'LE',
      'gt': 'GT',
      'ge': 'GE',
      'and': 'AND',
      'or': 'OR',
    };

    const op = opMap[instr.op];

    if (['eq', 'ne', 'lt', 'le', 'gt', 'ge'].includes(instr.op)) {
      // Comparison operations
      this.emitIndented(`CMP ${left}, ${right}`);
      this.emitIndented(`MOV ${dest}, #0`);
      this.emitIndented(`MOV${op} ${dest}, #1`);
    } else if (instr.op === 'and' || instr.op === 'or') {
      // Logical AND/OR
      if (dest !== left) {
        this.emitIndented(`MOV ${dest}, ${left}`);
      }
      this.emitIndented(`${op} ${dest}, ${dest}, ${right}`);
    } else {
      // Regular arithmetic/bitwise
      if (dest !== left) {
        this.emitIndented(`MOV ${dest}, ${left}`);
      }
      this.emitIndented(`${op} ${dest}, ${dest}, ${right}`);
    }
  }

  /**
   * Generate unary operation
   */
  private genUnaryOp(instr: IRUnaryOp): void {
    const dest = this.allocateRegister(instr.result.id);
    const operand = this.getOperand(instr.operand.id);

    const opMap: Record<UnaryOpKind, string> = {
      'neg': 'NEG',
      'not': 'NOT',
      'bitnot': 'NOT',
    };

    const op = opMap[instr.op];
    this.emitIndented(`${op} ${dest}, ${operand}`);
  }

  /**
   * Generate load instruction
   */
  private genLoad(instr: IRLoad): void {
    const dest = this.allocateRegister(instr.result.id);
    const addr = this.getOperand(instr.address.id);
    this.emitIndented(`LDR ${dest}, [${addr}]`);
  }

  /**
   * Generate store instruction
   */
  private genStore(instr: IRStore): void {
    const value = this.getOperand(instr.value.id);
    const addr = this.getOperand(instr.address.id);
    this.emitIndented(`STR ${value}, [${addr}]`);
  }

  /**
   * Generate function call
   */
  private genCall(instr: IRCall, func: IRFunction): void {
    // Place arguments in R0-R3, rest on stack
    for (let i = 0; i < instr.arguments.length; i++) {
      const arg = this.getOperand(instr.arguments[i].id);

      if (i < 4) {
        const argReg = `R${i}`;
        if (arg !== argReg) {
          this.emitIndented(`MOV ${argReg}, ${arg}`, `Arg ${i}`);
        }
      } else {
        this.emitIndented(`PUSH ${arg}`, `Arg ${i} (stack)`);
      }
    }

    this.emitIndented(`CALL ${instr.functionName}`);

    // Clean up stack args
    const stackArgs = Math.max(0, instr.arguments.length - 4);
    if (stackArgs > 0) {
      this.emitIndented(`ADD SP, SP, #${stackArgs * 4}`, 'Clean stack args');
    }

    // Get return value
    if (instr.result) {
      const dest = this.allocateRegister(instr.result.id);
      if (dest !== 'R0') {
        this.emitIndented(`MOV ${dest}, R0`, 'Get return value');
      }
    }
  }

  /**
   * Generate return instruction
   */
  private genReturn(instr: IRReturn, func: IRFunction): void {
    if (instr.value) {
      const value = this.getOperand(instr.value.id);
      if (value !== 'R0') {
        this.emitIndented(`MOV R0, ${value}`, 'Return value');
      }
    }

    this.emitEpilogue(func);
  }

  /**
   * Generate unconditional jump
   */
  private genJump(instr: IRJump): void {
    this.emitIndented(`JMP ${instr.target}`);
  }

  /**
   * Generate conditional jump
   */
  private genCondJump(instr: IRCondJump): void {
    const cond = this.getOperand(instr.condition.id);
    this.emitIndented(`CMP ${cond}, #0`);
    this.emitIndented(`JNZ ${instr.trueTarget}`, 'Jump if true');
    this.emitIndented(`JMP ${instr.falseTarget}`, 'Jump if false');
  }

  /**
   * Generate stack allocation
   */
  private genAlloc(instr: IRAlloc): void {
    const dest = this.allocateRegister(instr.result.id);
    const size = instr.allocatedType.size;

    // Allocate on stack and get pointer
    this.emitIndented(`SUB SP, SP, #${size}`, `Alloc ${size} bytes`);
    this.emitIndented(`MOV ${dest}, SP`, 'Get pointer to allocated space');
  }

  /**
   * Allocate a register for a value
   * Simple greedy allocation (can be improved with full register allocator)
   */
  private allocateRegister(valueId: number): string {
    if (this.context.valueToReg.has(valueId)) {
      return REG_NAMES[this.context.valueToReg.get(valueId)!];
    }

    // Use R4-R12 for allocation (R0-R3 for args, R13-R15 reserved)
    for (let reg = 4; reg <= 12; reg++) {
      if (!Array.from(this.context.valueToReg.values()).includes(reg)) {
        this.context.valueToReg.set(valueId, reg);
        return REG_NAMES[reg];
      }
    }

    // Spill to stack if no registers available
    const offset = this.context.currentStackOffset;
    this.context.currentStackOffset += 4;
    this.context.valueToStack.set(valueId, offset);
    this.context.spilledValues.add(valueId);

    return `[SP, #${offset}]`;
  }

  /**
   * Get operand string (register or stack location)
   */
  private getOperand(valueId: number): string {
    if (this.context.valueToReg.has(valueId)) {
      return REG_NAMES[this.context.valueToReg.get(valueId)!];
    }

    if (this.context.valueToStack.has(valueId)) {
      return `[SP, #${this.context.valueToStack.get(valueId)}]`;
    }

    // Temporary allocation
    return this.allocateRegister(valueId);
  }

  /**
   * Calculate stack space needed for function
   */
  private calculateStackSpace(func: IRFunction): number {
    // Count allocations
    let allocCount = 0;
    for (const block of func.blocks) {
      for (const instr of block.instructions) {
        if (instr.kind === 'alloc') {
          allocCount++;
        }
      }
    }

    // Space for locals + alignment
    const space = func.localCount * 4 + allocCount * 16;
    return Math.ceil(space / 16) * 16; // 16-byte alignment
  }

  /**
   * Order blocks for optimal code generation
   */
  private orderBlocks(func: IRFunction): IRBlock[] {
    // Simple ordering: entry block first, then others
    const ordered: IRBlock[] = [];
    const entryBlock = func.blocks.find(b => b.label === func.entryBlock);

    if (entryBlock) {
      ordered.push(entryBlock);
    }

    for (const block of func.blocks) {
      if (block.label !== func.entryBlock) {
        ordered.push(block);
      }
    }

    return ordered;
  }

  /**
   * Get or create string literal label
   */
  private getStringLabel(value: string): string {
    return `.str_${this.labelCounter++}`;
  }

  /**
   * Emit assembly line
   */
  private emit(line: string): void {
    this.context.output.push(line);
  }

  /**
   * Emit indented instruction
   */
  private emitIndented(instr: string, comment?: string): void {
    let line = this.context.indent + instr;
    if (comment) {
      line = line.padEnd(40) + `; ${comment}`;
    }
    this.emit(line);
  }

  /**
   * Reset code generation state
   */
  private reset(): void {
    this.context = {
      valueToReg: new Map(),
      valueToStack: new Map(),
      currentStackOffset: 0,
      spilledValues: new Set(),
      output: [],
      indent: '    ',
    };
    this.labelCounter = 0;
  }
}

/**
 * Convenience function to generate code from IR
 */
export function generateCode(program: IRProgram): string {
  const generator = new KVRMCodeGenerator();
  return generator.generate(program);
}
